# =============================================================================
# DO NOT DELETE OR RENAME THIS FILE.
#
# Despite the hash-style filename (and the hash-style revision ID inside),
# this migration IS in the active Alembic chain:
#
#     0002_add_client_address_phone
#       -> fee3ab30ec3c (this file)
#         -> 0003_timestamp_with_timezone
#
# 0003's down_revision points at 'fee3ab30ec3c'. If you delete this file,
# Alembic can no longer resolve the chain and the app refuses to boot with:
#   "Revision fee3ab30ec3c referenced from ... is not present"
#
# This has happened twice. Don't make it three. The filename was renamed
# from the original hash-only name to 0002a_* so it visually belongs to
# the numbered series, but the revision ID inside the file must remain
# 'fee3ab30ec3c' because 0003 references it by that exact string.
# =============================================================================
"""Add show_time_detail to invoices

Revision ID: fee3ab30ec3c
Revises: 
Create Date: 2026-05-02 00:16:28.424953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fee3ab30ec3c'
down_revision = '0002_add_client_address_phone'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('show_time_detail', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_column('show_time_detail')

    # ### end Alembic commands ###
