"""Add show_time_detail to invoices

Revision ID: fee3ab30ec3c
Revises: 
Create Date: 2026-05-02 00:16:28.424953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fee3ab30ec3c'
down_revision = '0002_add_client_address_phone'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('show_time_detail', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_column('show_time_detail')

    # ### end Alembic commands ###
